// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: crl.proto

package crl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CRLService_AddRevocation_FullMethodName = "/gigvault.crl.v1.CRLService/AddRevocation"
	CRLService_GetCRL_FullMethodName        = "/gigvault.crl.v1.CRLService/GetCRL"
	CRLService_PublishCRL_FullMethodName    = "/gigvault.crl.v1.CRLService/PublishCRL"
)

// CRLServiceClient is the client API for CRLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CRLService handles Certificate Revocation List operations
type CRLServiceClient interface {
	// AddRevocation adds a revoked certificate to the CRL
	AddRevocation(ctx context.Context, in *AddRevocationRequest, opts ...grpc.CallOption) (*AddRevocationResponse, error)
	// GetCRL retrieves the current CRL
	GetCRL(ctx context.Context, in *GetCRLRequest, opts ...grpc.CallOption) (*GetCRLResponse, error)
	// PublishCRL generates and publishes a new CRL
	PublishCRL(ctx context.Context, in *PublishCRLRequest, opts ...grpc.CallOption) (*PublishCRLResponse, error)
}

type cRLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCRLServiceClient(cc grpc.ClientConnInterface) CRLServiceClient {
	return &cRLServiceClient{cc}
}

func (c *cRLServiceClient) AddRevocation(ctx context.Context, in *AddRevocationRequest, opts ...grpc.CallOption) (*AddRevocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRevocationResponse)
	err := c.cc.Invoke(ctx, CRLService_AddRevocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRLServiceClient) GetCRL(ctx context.Context, in *GetCRLRequest, opts ...grpc.CallOption) (*GetCRLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCRLResponse)
	err := c.cc.Invoke(ctx, CRLService_GetCRL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRLServiceClient) PublishCRL(ctx context.Context, in *PublishCRLRequest, opts ...grpc.CallOption) (*PublishCRLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishCRLResponse)
	err := c.cc.Invoke(ctx, CRLService_PublishCRL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRLServiceServer is the server API for CRLService service.
// All implementations must embed UnimplementedCRLServiceServer
// for forward compatibility.
//
// CRLService handles Certificate Revocation List operations
type CRLServiceServer interface {
	// AddRevocation adds a revoked certificate to the CRL
	AddRevocation(context.Context, *AddRevocationRequest) (*AddRevocationResponse, error)
	// GetCRL retrieves the current CRL
	GetCRL(context.Context, *GetCRLRequest) (*GetCRLResponse, error)
	// PublishCRL generates and publishes a new CRL
	PublishCRL(context.Context, *PublishCRLRequest) (*PublishCRLResponse, error)
	mustEmbedUnimplementedCRLServiceServer()
}

// UnimplementedCRLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCRLServiceServer struct{}

func (UnimplementedCRLServiceServer) AddRevocation(context.Context, *AddRevocationRequest) (*AddRevocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRevocation not implemented")
}
func (UnimplementedCRLServiceServer) GetCRL(context.Context, *GetCRLRequest) (*GetCRLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCRL not implemented")
}
func (UnimplementedCRLServiceServer) PublishCRL(context.Context, *PublishCRLRequest) (*PublishCRLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishCRL not implemented")
}
func (UnimplementedCRLServiceServer) mustEmbedUnimplementedCRLServiceServer() {}
func (UnimplementedCRLServiceServer) testEmbeddedByValue()                    {}

// UnsafeCRLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CRLServiceServer will
// result in compilation errors.
type UnsafeCRLServiceServer interface {
	mustEmbedUnimplementedCRLServiceServer()
}

func RegisterCRLServiceServer(s grpc.ServiceRegistrar, srv CRLServiceServer) {
	// If the following call pancis, it indicates UnimplementedCRLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CRLService_ServiceDesc, srv)
}

func _CRLService_AddRevocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRevocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRLServiceServer).AddRevocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRLService_AddRevocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRLServiceServer).AddRevocation(ctx, req.(*AddRevocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRLService_GetCRL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCRLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRLServiceServer).GetCRL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRLService_GetCRL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRLServiceServer).GetCRL(ctx, req.(*GetCRLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRLService_PublishCRL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishCRLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRLServiceServer).PublishCRL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRLService_PublishCRL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRLServiceServer).PublishCRL(ctx, req.(*PublishCRLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CRLService_ServiceDesc is the grpc.ServiceDesc for CRLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CRLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gigvault.crl.v1.CRLService",
	HandlerType: (*CRLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRevocation",
			Handler:    _CRLService_AddRevocation_Handler,
		},
		{
			MethodName: "GetCRL",
			Handler:    _CRLService_GetCRL_Handler,
		},
		{
			MethodName: "PublishCRL",
			Handler:    _CRLService_PublishCRL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crl.proto",
}
