// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ca.proto

package ca

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignCSRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        string                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	ValidityDays  int32                  `protobuf:"varint,2,opt,name=validity_days,json=validityDays,proto3" json:"validity_days,omitempty"`
	Profile       string                 `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`                                                                                 // server, client, code-signing, etc.
	Extensions    map[string]string      `protobuf:"bytes,4,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional extensions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignCSRRequest) Reset() {
	*x = SignCSRRequest{}
	mi := &file_ca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRRequest) ProtoMessage() {}

func (x *SignCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRRequest.ProtoReflect.Descriptor instead.
func (*SignCSRRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{0}
}

func (x *SignCSRRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *SignCSRRequest) GetValidityDays() int32 {
	if x != nil {
		return x.ValidityDays
	}
	return 0
}

func (x *SignCSRRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SignCSRRequest) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type SignCSRResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem string                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	SerialNumber   string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	NotBefore      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignCSRResponse) Reset() {
	*x = SignCSRResponse{}
	mi := &file_ca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRResponse) ProtoMessage() {}

func (x *SignCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRResponse.ProtoReflect.Descriptor instead.
func (*SignCSRResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{1}
}

func (x *SignCSRResponse) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *SignCSRResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *SignCSRResponse) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *SignCSRResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

type GetCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	mi := &file_ca_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{2}
}

func (x *GetCertificateRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type GetCertificateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem   string                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	SerialNumber     string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	SubjectCn        string                 `protobuf:"bytes,3,opt,name=subject_cn,json=subjectCn,proto3" json:"subject_cn,omitempty"`
	IssuerCn         string                 `protobuf:"bytes,4,opt,name=issuer_cn,json=issuerCn,proto3" json:"issuer_cn,omitempty"`
	NotBefore        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // valid, revoked, expired
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	RevocationReason string                 `protobuf:"bytes,9,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCertificateResponse) Reset() {
	*x = GetCertificateResponse{}
	mi := &file_ca_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateResponse) ProtoMessage() {}

func (x *GetCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{3}
}

func (x *GetCertificateResponse) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *GetCertificateResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *GetCertificateResponse) GetSubjectCn() string {
	if x != nil {
		return x.SubjectCn
	}
	return ""
}

func (x *GetCertificateResponse) GetIssuerCn() string {
	if x != nil {
		return x.IssuerCn
	}
	return ""
}

func (x *GetCertificateResponse) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *GetCertificateResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *GetCertificateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetCertificateResponse) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *GetCertificateResponse) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

type ListCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // Filter by status (optional)
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesRequest) Reset() {
	*x = ListCertificatesRequest{}
	mi := &file_ca_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesRequest) ProtoMessage() {}

func (x *ListCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesRequest.ProtoReflect.Descriptor instead.
func (*ListCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{4}
}

func (x *ListCertificatesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListCertificatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCertificatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCertificatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*CertificateInfo     `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesResponse) Reset() {
	*x = ListCertificatesResponse{}
	mi := &file_ca_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesResponse) ProtoMessage() {}

func (x *ListCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesResponse.ProtoReflect.Descriptor instead.
func (*ListCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{5}
}

func (x *ListCertificatesResponse) GetCertificates() []*CertificateInfo {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *ListCertificatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CertificateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	SubjectCn     string                 `protobuf:"bytes,2,opt,name=subject_cn,json=subjectCn,proto3" json:"subject_cn,omitempty"`
	NotBefore     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateInfo) Reset() {
	*x = CertificateInfo{}
	mi := &file_ca_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateInfo) ProtoMessage() {}

func (x *CertificateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateInfo.ProtoReflect.Descriptor instead.
func (*CertificateInfo) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{6}
}

func (x *CertificateInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CertificateInfo) GetSubjectCn() string {
	if x != nil {
		return x.SubjectCn
	}
	return ""
}

func (x *CertificateInfo) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertificateInfo) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertificateInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RevokeCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // unspecified, keyCompromise, cACompromise, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateRequest) Reset() {
	*x = RevokeCertificateRequest{}
	mi := &file_ca_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateRequest) ProtoMessage() {}

func (x *RevokeCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateRequest.ProtoReflect.Descriptor instead.
func (*RevokeCertificateRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeCertificateRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *RevokeCertificateRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateResponse) Reset() {
	*x = RevokeCertificateResponse{}
	mi := &file_ca_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateResponse) ProtoMessage() {}

func (x *RevokeCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateResponse.ProtoReflect.Descriptor instead.
func (*RevokeCertificateResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeCertificateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeCertificateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RevokeCertificateResponse) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

var File_ca_proto protoreflect.FileDescriptor

const file_ca_proto_rawDesc = "" +
	"\n" +
	"\bca.proto\x12\x0egigvault.ca.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n" +
	"\x0eSignCSRRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\tR\x06csrPem\x12#\n" +
	"\rvalidity_days\x18\x02 \x01(\x05R\fvalidityDays\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x12N\n" +
	"\n" +
	"extensions\x18\x04 \x03(\v2..gigvault.ca.v1.SignCSRRequest.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\x0fSignCSRResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\tR\x0ecertificatePem\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x129\n" +
	"\n" +
	"not_before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"<\n" +
	"\x15GetCertificateRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\"\x96\x03\n" +
	"\x16GetCertificateResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\tR\x0ecertificatePem\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x1d\n" +
	"\n" +
	"subject_cn\x18\x03 \x01(\tR\tsubjectCn\x12\x1b\n" +
	"\tissuer_cn\x18\x04 \x01(\tR\bissuerCn\x129\n" +
	"\n" +
	"not_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"revoked_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12+\n" +
	"\x11revocation_reason\x18\t \x01(\tR\x10revocationReason\"m\n" +
	"\x17ListCertificatesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x87\x01\n" +
	"\x18ListCertificatesResponse\x12C\n" +
	"\fcertificates\x18\x01 \x03(\v2\x1f.gigvault.ca.v1.CertificateInfoR\fcertificates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xe1\x01\n" +
	"\x0fCertificateInfo\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12\x1d\n" +
	"\n" +
	"subject_cn\x18\x02 \x01(\tR\tsubjectCn\x129\n" +
	"\n" +
	"not_before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"W\n" +
	"\x18RevokeCertificateRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x8a\x01\n" +
	"\x19RevokeCertificateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt2\x89\x03\n" +
	"\tCAService\x12J\n" +
	"\aSignCSR\x12\x1e.gigvault.ca.v1.SignCSRRequest\x1a\x1f.gigvault.ca.v1.SignCSRResponse\x12_\n" +
	"\x0eGetCertificate\x12%.gigvault.ca.v1.GetCertificateRequest\x1a&.gigvault.ca.v1.GetCertificateResponse\x12e\n" +
	"\x10ListCertificates\x12'.gigvault.ca.v1.ListCertificatesRequest\x1a(.gigvault.ca.v1.ListCertificatesResponse\x12h\n" +
	"\x11RevokeCertificate\x12(.gigvault.ca.v1.RevokeCertificateRequest\x1a).gigvault.ca.v1.RevokeCertificateResponseB)Z'github.com/gigvault/shared/api/proto/cab\x06proto3"

var (
	file_ca_proto_rawDescOnce sync.Once
	file_ca_proto_rawDescData []byte
)

func file_ca_proto_rawDescGZIP() []byte {
	file_ca_proto_rawDescOnce.Do(func() {
		file_ca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ca_proto_rawDesc), len(file_ca_proto_rawDesc)))
	})
	return file_ca_proto_rawDescData
}

var file_ca_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ca_proto_goTypes = []any{
	(*SignCSRRequest)(nil),            // 0: gigvault.ca.v1.SignCSRRequest
	(*SignCSRResponse)(nil),           // 1: gigvault.ca.v1.SignCSRResponse
	(*GetCertificateRequest)(nil),     // 2: gigvault.ca.v1.GetCertificateRequest
	(*GetCertificateResponse)(nil),    // 3: gigvault.ca.v1.GetCertificateResponse
	(*ListCertificatesRequest)(nil),   // 4: gigvault.ca.v1.ListCertificatesRequest
	(*ListCertificatesResponse)(nil),  // 5: gigvault.ca.v1.ListCertificatesResponse
	(*CertificateInfo)(nil),           // 6: gigvault.ca.v1.CertificateInfo
	(*RevokeCertificateRequest)(nil),  // 7: gigvault.ca.v1.RevokeCertificateRequest
	(*RevokeCertificateResponse)(nil), // 8: gigvault.ca.v1.RevokeCertificateResponse
	nil,                               // 9: gigvault.ca.v1.SignCSRRequest.ExtensionsEntry
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
}
var file_ca_proto_depIdxs = []int32{
	9,  // 0: gigvault.ca.v1.SignCSRRequest.extensions:type_name -> gigvault.ca.v1.SignCSRRequest.ExtensionsEntry
	10, // 1: gigvault.ca.v1.SignCSRResponse.not_before:type_name -> google.protobuf.Timestamp
	10, // 2: gigvault.ca.v1.SignCSRResponse.not_after:type_name -> google.protobuf.Timestamp
	10, // 3: gigvault.ca.v1.GetCertificateResponse.not_before:type_name -> google.protobuf.Timestamp
	10, // 4: gigvault.ca.v1.GetCertificateResponse.not_after:type_name -> google.protobuf.Timestamp
	10, // 5: gigvault.ca.v1.GetCertificateResponse.revoked_at:type_name -> google.protobuf.Timestamp
	6,  // 6: gigvault.ca.v1.ListCertificatesResponse.certificates:type_name -> gigvault.ca.v1.CertificateInfo
	10, // 7: gigvault.ca.v1.CertificateInfo.not_before:type_name -> google.protobuf.Timestamp
	10, // 8: gigvault.ca.v1.CertificateInfo.not_after:type_name -> google.protobuf.Timestamp
	10, // 9: gigvault.ca.v1.RevokeCertificateResponse.revoked_at:type_name -> google.protobuf.Timestamp
	0,  // 10: gigvault.ca.v1.CAService.SignCSR:input_type -> gigvault.ca.v1.SignCSRRequest
	2,  // 11: gigvault.ca.v1.CAService.GetCertificate:input_type -> gigvault.ca.v1.GetCertificateRequest
	4,  // 12: gigvault.ca.v1.CAService.ListCertificates:input_type -> gigvault.ca.v1.ListCertificatesRequest
	7,  // 13: gigvault.ca.v1.CAService.RevokeCertificate:input_type -> gigvault.ca.v1.RevokeCertificateRequest
	1,  // 14: gigvault.ca.v1.CAService.SignCSR:output_type -> gigvault.ca.v1.SignCSRResponse
	3,  // 15: gigvault.ca.v1.CAService.GetCertificate:output_type -> gigvault.ca.v1.GetCertificateResponse
	5,  // 16: gigvault.ca.v1.CAService.ListCertificates:output_type -> gigvault.ca.v1.ListCertificatesResponse
	8,  // 17: gigvault.ca.v1.CAService.RevokeCertificate:output_type -> gigvault.ca.v1.RevokeCertificateResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ca_proto_init() }
func file_ca_proto_init() {
	if File_ca_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ca_proto_rawDesc), len(file_ca_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ca_proto_goTypes,
		DependencyIndexes: file_ca_proto_depIdxs,
		MessageInfos:      file_ca_proto_msgTypes,
	}.Build()
	File_ca_proto = out.File
	file_ca_proto_goTypes = nil
	file_ca_proto_depIdxs = nil
}
