// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: crl.proto

package crlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRevocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // unspecified, keyCompromise, cACompromise, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRevocationRequest) Reset() {
	*x = AddRevocationRequest{}
	mi := &file_crl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRevocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRevocationRequest) ProtoMessage() {}

func (x *AddRevocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRevocationRequest.ProtoReflect.Descriptor instead.
func (*AddRevocationRequest) Descriptor() ([]byte, []int) {
	return file_crl_proto_rawDescGZIP(), []int{0}
}

func (x *AddRevocationRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *AddRevocationRequest) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *AddRevocationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AddRevocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRevocationResponse) Reset() {
	*x = AddRevocationResponse{}
	mi := &file_crl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRevocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRevocationResponse) ProtoMessage() {}

func (x *AddRevocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRevocationResponse.ProtoReflect.Descriptor instead.
func (*AddRevocationResponse) Descriptor() ([]byte, []int) {
	return file_crl_proto_rawDescGZIP(), []int{1}
}

func (x *AddRevocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddRevocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCRLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"` // CA common name (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLRequest) Reset() {
	*x = GetCRLRequest{}
	mi := &file_crl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLRequest) ProtoMessage() {}

func (x *GetCRLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLRequest.ProtoReflect.Descriptor instead.
func (*GetCRLRequest) Descriptor() ([]byte, []int) {
	return file_crl_proto_rawDescGZIP(), []int{2}
}

func (x *GetCRLRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type GetCRLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CrlDer        []byte                 `protobuf:"bytes,1,opt,name=crl_der,json=crlDer,proto3" json:"crl_der,omitempty"` // CRL in DER format
	CrlPem        string                 `protobuf:"bytes,2,opt,name=crl_pem,json=crlPem,proto3" json:"crl_pem,omitempty"` // CRL in PEM format
	ThisUpdate    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=this_update,json=thisUpdate,proto3" json:"this_update,omitempty"`
	NextUpdate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_update,json=nextUpdate,proto3" json:"next_update,omitempty"`
	RevokedCount  int32                  `protobuf:"varint,5,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLResponse) Reset() {
	*x = GetCRLResponse{}
	mi := &file_crl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLResponse) ProtoMessage() {}

func (x *GetCRLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLResponse.ProtoReflect.Descriptor instead.
func (*GetCRLResponse) Descriptor() ([]byte, []int) {
	return file_crl_proto_rawDescGZIP(), []int{3}
}

func (x *GetCRLResponse) GetCrlDer() []byte {
	if x != nil {
		return x.CrlDer
	}
	return nil
}

func (x *GetCRLResponse) GetCrlPem() string {
	if x != nil {
		return x.CrlPem
	}
	return ""
}

func (x *GetCRLResponse) GetThisUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.ThisUpdate
	}
	return nil
}

func (x *GetCRLResponse) GetNextUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextUpdate
	}
	return nil
}

func (x *GetCRLResponse) GetRevokedCount() int32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

type PublishCRLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"` // Force generation even if not needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCRLRequest) Reset() {
	*x = PublishCRLRequest{}
	mi := &file_crl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCRLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCRLRequest) ProtoMessage() {}

func (x *PublishCRLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCRLRequest.ProtoReflect.Descriptor instead.
func (*PublishCRLRequest) Descriptor() ([]byte, []int) {
	return file_crl_proto_rawDescGZIP(), []int{4}
}

func (x *PublishCRLRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type PublishCRLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	RevokedCount  int32                  `protobuf:"varint,4,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCRLResponse) Reset() {
	*x = PublishCRLResponse{}
	mi := &file_crl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCRLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCRLResponse) ProtoMessage() {}

func (x *PublishCRLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCRLResponse.ProtoReflect.Descriptor instead.
func (*PublishCRLResponse) Descriptor() ([]byte, []int) {
	return file_crl_proto_rawDescGZIP(), []int{5}
}

func (x *PublishCRLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishCRLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublishCRLResponse) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *PublishCRLResponse) GetRevokedCount() int32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

var File_crl_proto protoreflect.FileDescriptor

const file_crl_proto_rawDesc = "" +
	"\n" +
	"\tcrl.proto\x12\x0fgigvault.crl.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\x14AddRevocationRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x129\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"K\n" +
	"\x15AddRevocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\rGetCRLRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\"\xe1\x01\n" +
	"\x0eGetCRLResponse\x12\x17\n" +
	"\acrl_der\x18\x01 \x01(\fR\x06crlDer\x12\x17\n" +
	"\acrl_pem\x18\x02 \x01(\tR\x06crlPem\x12;\n" +
	"\vthis_update\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"thisUpdate\x12;\n" +
	"\vnext_update\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"nextUpdate\x12#\n" +
	"\rrevoked_count\x18\x05 \x01(\x05R\frevokedCount\")\n" +
	"\x11PublishCRLRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"\xac\x01\n" +
	"\x12PublishCRLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\fpublished_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12#\n" +
	"\rrevoked_count\x18\x04 \x01(\x05R\frevokedCount2\x8e\x02\n" +
	"\n" +
	"CRLService\x12^\n" +
	"\rAddRevocation\x12%.gigvault.crl.v1.AddRevocationRequest\x1a&.gigvault.crl.v1.AddRevocationResponse\x12I\n" +
	"\x06GetCRL\x12\x1e.gigvault.crl.v1.GetCRLRequest\x1a\x1f.gigvault.crl.v1.GetCRLResponse\x12U\n" +
	"\n" +
	"PublishCRL\x12\".gigvault.crl.v1.PublishCRLRequest\x1a#.gigvault.crl.v1.PublishCRLResponseB0Z.github.com/gigvault/shared/api/proto/crl;crlpbb\x06proto3"

var (
	file_crl_proto_rawDescOnce sync.Once
	file_crl_proto_rawDescData []byte
)

func file_crl_proto_rawDescGZIP() []byte {
	file_crl_proto_rawDescOnce.Do(func() {
		file_crl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crl_proto_rawDesc), len(file_crl_proto_rawDesc)))
	})
	return file_crl_proto_rawDescData
}

var file_crl_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_crl_proto_goTypes = []any{
	(*AddRevocationRequest)(nil),  // 0: gigvault.crl.v1.AddRevocationRequest
	(*AddRevocationResponse)(nil), // 1: gigvault.crl.v1.AddRevocationResponse
	(*GetCRLRequest)(nil),         // 2: gigvault.crl.v1.GetCRLRequest
	(*GetCRLResponse)(nil),        // 3: gigvault.crl.v1.GetCRLResponse
	(*PublishCRLRequest)(nil),     // 4: gigvault.crl.v1.PublishCRLRequest
	(*PublishCRLResponse)(nil),    // 5: gigvault.crl.v1.PublishCRLResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_crl_proto_depIdxs = []int32{
	6, // 0: gigvault.crl.v1.AddRevocationRequest.revoked_at:type_name -> google.protobuf.Timestamp
	6, // 1: gigvault.crl.v1.GetCRLResponse.this_update:type_name -> google.protobuf.Timestamp
	6, // 2: gigvault.crl.v1.GetCRLResponse.next_update:type_name -> google.protobuf.Timestamp
	6, // 3: gigvault.crl.v1.PublishCRLResponse.published_at:type_name -> google.protobuf.Timestamp
	0, // 4: gigvault.crl.v1.CRLService.AddRevocation:input_type -> gigvault.crl.v1.AddRevocationRequest
	2, // 5: gigvault.crl.v1.CRLService.GetCRL:input_type -> gigvault.crl.v1.GetCRLRequest
	4, // 6: gigvault.crl.v1.CRLService.PublishCRL:input_type -> gigvault.crl.v1.PublishCRLRequest
	1, // 7: gigvault.crl.v1.CRLService.AddRevocation:output_type -> gigvault.crl.v1.AddRevocationResponse
	3, // 8: gigvault.crl.v1.CRLService.GetCRL:output_type -> gigvault.crl.v1.GetCRLResponse
	5, // 9: gigvault.crl.v1.CRLService.PublishCRL:output_type -> gigvault.crl.v1.PublishCRLResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_crl_proto_init() }
func file_crl_proto_init() {
	if File_crl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crl_proto_rawDesc), len(file_crl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crl_proto_goTypes,
		DependencyIndexes: file_crl_proto_depIdxs,
		MessageInfos:      file_crl_proto_msgTypes,
	}.Build()
	File_crl_proto = out.File
	file_crl_proto_goTypes = nil
	file_crl_proto_depIdxs = nil
}
