// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: ocsp.proto

package ocsp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OCSPService_UpdateStatus_FullMethodName      = "/gigvault.ocsp.v1.OCSPService/UpdateStatus"
	OCSPService_CheckStatus_FullMethodName       = "/gigvault.ocsp.v1.OCSPService/CheckStatus"
	OCSPService_BatchUpdateStatus_FullMethodName = "/gigvault.ocsp.v1.OCSPService/BatchUpdateStatus"
)

// OCSPServiceClient is the client API for OCSPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OCSPService handles Online Certificate Status Protocol operations
type OCSPServiceClient interface {
	// UpdateStatus updates the status of a certificate
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error)
	// CheckStatus checks the status of a certificate
	CheckStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error)
	// BatchUpdateStatus updates status for multiple certificates
	BatchUpdateStatus(ctx context.Context, in *BatchUpdateStatusRequest, opts ...grpc.CallOption) (*BatchUpdateStatusResponse, error)
}

type oCSPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOCSPServiceClient(cc grpc.ClientConnInterface) OCSPServiceClient {
	return &oCSPServiceClient{cc}
}

func (c *oCSPServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatusResponse)
	err := c.cc.Invoke(ctx, OCSPService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCSPServiceClient) CheckStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStatusResponse)
	err := c.cc.Invoke(ctx, OCSPService_CheckStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCSPServiceClient) BatchUpdateStatus(ctx context.Context, in *BatchUpdateStatusRequest, opts ...grpc.CallOption) (*BatchUpdateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdateStatusResponse)
	err := c.cc.Invoke(ctx, OCSPService_BatchUpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OCSPServiceServer is the server API for OCSPService service.
// All implementations must embed UnimplementedOCSPServiceServer
// for forward compatibility.
//
// OCSPService handles Online Certificate Status Protocol operations
type OCSPServiceServer interface {
	// UpdateStatus updates the status of a certificate
	UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error)
	// CheckStatus checks the status of a certificate
	CheckStatus(context.Context, *CheckStatusRequest) (*CheckStatusResponse, error)
	// BatchUpdateStatus updates status for multiple certificates
	BatchUpdateStatus(context.Context, *BatchUpdateStatusRequest) (*BatchUpdateStatusResponse, error)
	mustEmbedUnimplementedOCSPServiceServer()
}

// UnimplementedOCSPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOCSPServiceServer struct{}

func (UnimplementedOCSPServiceServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedOCSPServiceServer) CheckStatus(context.Context, *CheckStatusRequest) (*CheckStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStatus not implemented")
}
func (UnimplementedOCSPServiceServer) BatchUpdateStatus(context.Context, *BatchUpdateStatusRequest) (*BatchUpdateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpdateStatus not implemented")
}
func (UnimplementedOCSPServiceServer) mustEmbedUnimplementedOCSPServiceServer() {}
func (UnimplementedOCSPServiceServer) testEmbeddedByValue()                     {}

// UnsafeOCSPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OCSPServiceServer will
// result in compilation errors.
type UnsafeOCSPServiceServer interface {
	mustEmbedUnimplementedOCSPServiceServer()
}

func RegisterOCSPServiceServer(s grpc.ServiceRegistrar, srv OCSPServiceServer) {
	// If the following call pancis, it indicates UnimplementedOCSPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OCSPService_ServiceDesc, srv)
}

func _OCSPService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCSPServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCSPService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCSPServiceServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCSPService_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCSPServiceServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCSPService_CheckStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCSPServiceServer).CheckStatus(ctx, req.(*CheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCSPService_BatchUpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCSPServiceServer).BatchUpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCSPService_BatchUpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCSPServiceServer).BatchUpdateStatus(ctx, req.(*BatchUpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OCSPService_ServiceDesc is the grpc.ServiceDesc for OCSPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OCSPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gigvault.ocsp.v1.OCSPService",
	HandlerType: (*OCSPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStatus",
			Handler:    _OCSPService_UpdateStatus_Handler,
		},
		{
			MethodName: "CheckStatus",
			Handler:    _OCSPService_CheckStatus_Handler,
		},
		{
			MethodName: "BatchUpdateStatus",
			Handler:    _OCSPService_BatchUpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocsp.proto",
}
