// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ocsp.proto

package ocsp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber     string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                             // good, revoked, unknown
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`                      // Only for revoked status
	RevocationReason string                 `protobuf:"bytes,4,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"` // Only for revoked status
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_ocsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_ocsp_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateStatusRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateStatusRequest) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *UpdateStatusRequest) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_ocsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_ocsp_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusRequest) Reset() {
	*x = CheckStatusRequest{}
	mi := &file_ocsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusRequest) ProtoMessage() {}

func (x *CheckStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckStatusRequest) Descriptor() ([]byte, []int) {
	return file_ocsp_proto_rawDescGZIP(), []int{2}
}

func (x *CheckStatusRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type CheckStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // good, revoked, unknown
	ThisUpdate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=this_update,json=thisUpdate,proto3" json:"this_update,omitempty"`
	NextUpdate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=next_update,json=nextUpdate,proto3" json:"next_update,omitempty"`
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`                      // Only for revoked
	RevocationReason string                 `protobuf:"bytes,5,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"` // Only for revoked
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckStatusResponse) Reset() {
	*x = CheckStatusResponse{}
	mi := &file_ocsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusResponse) ProtoMessage() {}

func (x *CheckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckStatusResponse) Descriptor() ([]byte, []int) {
	return file_ocsp_proto_rawDescGZIP(), []int{3}
}

func (x *CheckStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckStatusResponse) GetThisUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.ThisUpdate
	}
	return nil
}

func (x *CheckStatusResponse) GetNextUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextUpdate
	}
	return nil
}

func (x *CheckStatusResponse) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *CheckStatusResponse) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

type BatchUpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*UpdateStatusRequest `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateStatusRequest) Reset() {
	*x = BatchUpdateStatusRequest{}
	mi := &file_ocsp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateStatusRequest) ProtoMessage() {}

func (x *BatchUpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocsp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_ocsp_proto_rawDescGZIP(), []int{4}
}

func (x *BatchUpdateStatusRequest) GetUpdates() []*UpdateStatusRequest {
	if x != nil {
		return x.Updates
	}
	return nil
}

type BatchUpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  int32                  `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateStatusResponse) Reset() {
	*x = BatchUpdateStatusResponse{}
	mi := &file_ocsp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateStatusResponse) ProtoMessage() {}

func (x *BatchUpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocsp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_ocsp_proto_rawDescGZIP(), []int{5}
}

func (x *BatchUpdateStatusResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchUpdateStatusResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BatchUpdateStatusResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_ocsp_proto protoreflect.FileDescriptor

const file_ocsp_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ocsp.proto\x12\x10gigvault.ocsp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\x13UpdateStatusRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12+\n" +
	"\x11revocation_reason\x18\x04 \x01(\tR\x10revocationReason\"J\n" +
	"\x14UpdateStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x12CheckStatusRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\"\x8f\x02\n" +
	"\x13CheckStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12;\n" +
	"\vthis_update\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"thisUpdate\x12;\n" +
	"\vnext_update\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"nextUpdate\x129\n" +
	"\n" +
	"revoked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12+\n" +
	"\x11revocation_reason\x18\x05 \x01(\tR\x10revocationReason\"[\n" +
	"\x18BatchUpdateStatusRequest\x12?\n" +
	"\aupdates\x18\x01 \x03(\v2%.gigvault.ocsp.v1.UpdateStatusRequestR\aupdates\"}\n" +
	"\x19BatchUpdateStatusResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x05R\ffailureCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors2\xb6\x02\n" +
	"\vOCSPService\x12]\n" +
	"\fUpdateStatus\x12%.gigvault.ocsp.v1.UpdateStatusRequest\x1a&.gigvault.ocsp.v1.UpdateStatusResponse\x12Z\n" +
	"\vCheckStatus\x12$.gigvault.ocsp.v1.CheckStatusRequest\x1a%.gigvault.ocsp.v1.CheckStatusResponse\x12l\n" +
	"\x11BatchUpdateStatus\x12*.gigvault.ocsp.v1.BatchUpdateStatusRequest\x1a+.gigvault.ocsp.v1.BatchUpdateStatusResponseB+Z)github.com/gigvault/shared/api/proto/ocspb\x06proto3"

var (
	file_ocsp_proto_rawDescOnce sync.Once
	file_ocsp_proto_rawDescData []byte
)

func file_ocsp_proto_rawDescGZIP() []byte {
	file_ocsp_proto_rawDescOnce.Do(func() {
		file_ocsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocsp_proto_rawDesc), len(file_ocsp_proto_rawDesc)))
	})
	return file_ocsp_proto_rawDescData
}

var file_ocsp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ocsp_proto_goTypes = []any{
	(*UpdateStatusRequest)(nil),       // 0: gigvault.ocsp.v1.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),      // 1: gigvault.ocsp.v1.UpdateStatusResponse
	(*CheckStatusRequest)(nil),        // 2: gigvault.ocsp.v1.CheckStatusRequest
	(*CheckStatusResponse)(nil),       // 3: gigvault.ocsp.v1.CheckStatusResponse
	(*BatchUpdateStatusRequest)(nil),  // 4: gigvault.ocsp.v1.BatchUpdateStatusRequest
	(*BatchUpdateStatusResponse)(nil), // 5: gigvault.ocsp.v1.BatchUpdateStatusResponse
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_ocsp_proto_depIdxs = []int32{
	6, // 0: gigvault.ocsp.v1.UpdateStatusRequest.revoked_at:type_name -> google.protobuf.Timestamp
	6, // 1: gigvault.ocsp.v1.CheckStatusResponse.this_update:type_name -> google.protobuf.Timestamp
	6, // 2: gigvault.ocsp.v1.CheckStatusResponse.next_update:type_name -> google.protobuf.Timestamp
	6, // 3: gigvault.ocsp.v1.CheckStatusResponse.revoked_at:type_name -> google.protobuf.Timestamp
	0, // 4: gigvault.ocsp.v1.BatchUpdateStatusRequest.updates:type_name -> gigvault.ocsp.v1.UpdateStatusRequest
	0, // 5: gigvault.ocsp.v1.OCSPService.UpdateStatus:input_type -> gigvault.ocsp.v1.UpdateStatusRequest
	2, // 6: gigvault.ocsp.v1.OCSPService.CheckStatus:input_type -> gigvault.ocsp.v1.CheckStatusRequest
	4, // 7: gigvault.ocsp.v1.OCSPService.BatchUpdateStatus:input_type -> gigvault.ocsp.v1.BatchUpdateStatusRequest
	1, // 8: gigvault.ocsp.v1.OCSPService.UpdateStatus:output_type -> gigvault.ocsp.v1.UpdateStatusResponse
	3, // 9: gigvault.ocsp.v1.OCSPService.CheckStatus:output_type -> gigvault.ocsp.v1.CheckStatusResponse
	5, // 10: gigvault.ocsp.v1.OCSPService.BatchUpdateStatus:output_type -> gigvault.ocsp.v1.BatchUpdateStatusResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ocsp_proto_init() }
func file_ocsp_proto_init() {
	if File_ocsp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsp_proto_rawDesc), len(file_ocsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocsp_proto_goTypes,
		DependencyIndexes: file_ocsp_proto_depIdxs,
		MessageInfos:      file_ocsp_proto_msgTypes,
	}.Build()
	File_ocsp_proto = out.File
	file_ocsp_proto_goTypes = nil
	file_ocsp_proto_depIdxs = nil
}
